name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PUBLISH_TO_NUGET_ORG}}

      - name: Build
        run: dotnet build --configuration Release

      - name: Create the package
        run: dotnet pack --configuration Release

      - name: Publish the package to nuget.org
        run: dotnet nuget push "**/*.nupkg" --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PUBLISH_TO_NUGET_ORG }}
